/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package csdlpt_9_10;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kiet
 */
public class ManHinhChinh extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChinh
     */
    public ManHinhChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenTruong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenDuHocSinh = new javax.swing.JTextField();
        TenChuyenNghanh = new javax.swing.JTextField();
        btnDST = new javax.swing.JButton();
        btnDSDHSDK = new javax.swing.JButton();
        btnDSDHS = new javax.swing.JButton();
        btnDSTDDK = new javax.swing.JButton();
        btnDSCN = new javax.swing.JButton();
        btnDSDHSDKCN = new javax.swing.JButton();
        btnDHSRot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTenTruong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTruongActionPerformed(evt);
            }
        });

        jLabel1.setText("TenTruong");

        txtError.setColumns(20);
        txtError.setRows(5);
        jScrollPane1.setViewportView(txtError);

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblResult);

        jLabel2.setText("Thông báo lỗi");

        jLabel3.setText("TenDuHocSInh");

        jLabel4.setText("TenChuyenNghanh");

        jLabel5.setText("Bảng kết quả");

        btnDST.setText("DanhSachTruong");
        btnDST.setToolTipText("");
        btnDST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSTActionPerformed(evt);
            }
        });

        btnDSDHSDK.setText("DanhSachDuHocSinhDangKy");
        btnDSDHSDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSDHSDKActionPerformed(evt);
            }
        });

        btnDSDHS.setText("DanhSachDuHocSinh");
        btnDSDHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSDHSActionPerformed(evt);
            }
        });

        btnDSTDDK.setText("DanhSachTruongDaDangKy");

        btnDSCN.setText("DanhSachChuyenNghanh");
        btnDSCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSCNActionPerformed(evt);
            }
        });

        btnDSDHSDKCN.setText("DSDuHocSinhDKChuyenNghanh");

        btnDHSRot.setText("DHSRot");
        btnDHSRot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDHSRotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenTruong, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTenDuHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TenChuyenNghanh, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnDST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnDSDHS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnDSCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(383, 383, 383)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDSDHSDK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDSTDDK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDSDHSDKCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDHSRot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenTruong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnDST)
                    .addComponent(btnDSDHSDK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenDuHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDSDHS)
                    .addComponent(btnDSTDDK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenChuyenNghanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDSCN)
                    .addComponent(btnDSDHSDKCN))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDHSRot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenTruongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTruongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTruongActionPerformed

    private void btnDSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSTActionPerformed
        // TODO add your handling code here:
        try {
            File f1 = new File("D:\\Download\\Data\\server_1.txt");
            File f2 = new File("D:\\Download\\Data\\server_2.txt");

            DataModel db = new DataModel();
            String tenCot[] = {"MATR", "TENTRUONG", "QUOCGIA"};
            tblmodel = new DefaultTableModel(tenCot, 0);

            // * Lay tat ca manh ngang
            ArrayList<ArrayList<String>> data2 = db.getManhTruongHoc(f1, tblmodel, tblResult, txtError, tenCot, "2"); // Server 1
            ArrayList<ArrayList<String>> data3 = db.getManhTruongHoc(f1, tblmodel, tblResult, txtError, tenCot, "3"); // Server 2
            ArrayList<ArrayList<String>> data4 = db.getManhTruongHoc(f1, tblmodel, tblResult, txtError, tenCot, "4"); // Server 2

            // * gộp 3 mảnh ngang 
            ArrayList<ArrayList<String>> combinedData = db.gopManh(data2, data3, data4);

            // * Lấy dữ liệu của mảnh dọc
            String tenCot1[] = {"MATR", "HOCPHI"};
            ArrayList<ArrayList<String>> data1 = db.getManhTruongHoc(f1, tblmodel, tblResult, txtError, tenCot1, "1"); // Server 1

            // * Gộp 3 mảnh ngang này với mảnh 1 (mảnh dọc)
            String tenCotAll[] = {"MATR", "TENTRUONG", "QUOCGIA", "HOCPHI"};
            ArrayList<ArrayList<String>> c = db.ket(combinedData, data1);
            tblmodel = db.getTableModel(tenCotAll, c);
            tblResult.setModel(tblmodel);

        } catch (Exception e) {
            txtError.setText(e.getMessage());
        }
    }//GEN-LAST:event_btnDSTActionPerformed

    private void btnDSDHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSDHSActionPerformed
        // TODO add your handling code here:
        try {
            File f1 = new File("D:\\Download\\Data\\server_1.txt");
            File f2 = new File("D:\\Download\\Data\\server_2.txt");

            DataModel db = new DataModel();
            String tenCot[] = {"MADHS", "HOTEN", "DIEMTB", "IELTS"};
            tblmodel = new DefaultTableModel(tenCot, 0);

            // * Lay tat ca manh ngang
            ArrayList<ArrayList<String>> data1 = db.getManhDuHocSinh(f1, tblmodel, tblResult, txtError, tenCot, "1"); // Server 1
            ArrayList<ArrayList<String>> data2 = db.getManhDuHocSinh(f1, tblmodel, tblResult, txtError, tenCot, "2"); // Server 1

            // * gộp 2 mảnh ngang 
            ArrayList<ArrayList<String>> combinedData = db.gopManh(data1, data2);

            // * Lấy dữ liệu của mảnh dọc
            String tenCot1[] = {"MADHS", "DIACHI", "TAICHINH", "DONVI"};
            ArrayList<ArrayList<String>> data3 = db.getManhDuHocSinh(f1, tblmodel, tblResult, txtError, tenCot1, "3"); // Server 2

            // * Gộp 3 mảnh ngang này với mảnh 1 (mảnh dọc)
            String tenCotAll[] = {"MADHS", "HOTEN", "DIEMTB", "IELTS", "DIACHI", "TAICHINH", "DONVI"};
            ArrayList<ArrayList<String>> c = db.ket(combinedData, data3);
            tblmodel = db.getTableModel(tenCotAll, c);
            tblResult.setModel(tblmodel);

        } catch (Exception e) {
            txtError.setText(e.getMessage());
        }
    }//GEN-LAST:event_btnDSDHSActionPerformed

    private void btnDSCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSCNActionPerformed
        // TODO add your handling code here:
        try {
            File f1 = new File("D:\\Download\\Data\\server_1.txt");
            File f2 = new File("D:\\Download\\Data\\server_2.txt");

            DataModel db = new DataModel();
            String tenCot1[] = {"MANG", "TENNGANH", "IELTS"};
            tblmodel = new DefaultTableModel(tenCot1, 0);

            // * Lấy Mảnh 1
            ArrayList<ArrayList<String>> data1 = db.getManhNganhHoc(f1, tblmodel, tblResult, txtError, tenCot1, "1"); // Server 1

            // * Lấy Mảnh 2
            String tenCot2[] = {"MANG", "SONAM"};
            ArrayList<ArrayList<String>> data2 = db.getManhNganhHoc(f1, tblmodel, tblResult, txtError, tenCot2, "2"); // Server 2

            // * Gộp 2 mảnh ngang này với mảnh 1 (mảnh dọc)
            String tenCotAll[] = {"MANG", "TENNGANH", "IELTS", "SONAM"};
            ArrayList<ArrayList<String>> c = db.ket(data1, data2);
            tblmodel = db.getTableModel(tenCotAll, c);
            tblResult.setModel(tblmodel);

        } catch (Exception e) {
            txtError.setText(e.getMessage());
        }
    }//GEN-LAST:event_btnDSCNActionPerformed

    private void btnDSDHSDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSDHSDKActionPerformed
        // TODO add your handling code here:
        File f1 = new File("D:\\Download\\Data\\server_1.txt");
        File f2 = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenTruong = txtTenTruong.getText().trim();
        if (tenTruong.isEmpty()) {
            txtError.setText("Vui lòng nhập tên trường!");
        } else {
            // * Lấy tất cả dữ liệu của bảng Trường học
            String tenCotTruong[] = {"MATR", "TENTRUONG", "QUOCGIA"};
            tblmodel = new DefaultTableModel(tenCotTruong, 0);

            // * Lay tat ca manh ngang
            ArrayList<ArrayList<String>> truonghoc_2 = db.getManhTruongHoc(f1, tblmodel, tblResult, txtError, tenCotTruong, "2"); // Server 1
            ArrayList<ArrayList<String>> truonghoc_3 = db.getManhTruongHoc(f1, tblmodel, tblResult, txtError, tenCotTruong, "3"); // Server 2
            ArrayList<ArrayList<String>> truonghoc_4 = db.getManhTruongHoc(f1, tblmodel, tblResult, txtError, tenCotTruong, "4"); // Server 2

            // * gộp 3 mảnh ngang 
            ArrayList<ArrayList<String>> combinedTruongHoc = db.gopManh(truonghoc_2, truonghoc_3, truonghoc_4);

            // * Lấy dữ liệu của mảnh dọc
            String tenCotTruong1[] = {"MATR", "HOCPHI"};
            ArrayList<ArrayList<String>> truonghoc_1 = db.getManhTruongHoc(f1, tblmodel, tblResult, txtError, tenCotTruong1, "1"); // Server 1

            // * Gộp 3 mảnh ngang này với mảnh 1 (mảnh dọc)
//            String tenCotTruongAll[] = {"MATR", "TENTRUONG", "QUOCGIA", "HOCPHI"};
            ArrayList<ArrayList<String>> truonghoc = db.ket(combinedTruongHoc, truonghoc_1);

            // *-------------------------------------------
            // * Lấy tất cả dữ liệu của bảng Du Học Sinh
            String tenCotDHS[] = {"MADHS", "HOTEN", "DIEMTB", "IELTS"};
            tblmodel = new DefaultTableModel(tenCotDHS, 0);

            // * Lay tat ca manh ngang
            ArrayList<ArrayList<String>> duhocsinh_1 = db.getManhDuHocSinh(f1, tblmodel, tblResult, txtError, tenCotDHS, "1"); // Server 1
            ArrayList<ArrayList<String>> duhocsinh_2 = db.getManhDuHocSinh(f1, tblmodel, tblResult, txtError, tenCotDHS, "2"); // Server 1

            // * gộp 2 mảnh ngang 
            ArrayList<ArrayList<String>> combinedDuHocSinh = db.gopManh(duhocsinh_1, duhocsinh_2);

            // * Lấy dữ liệu của mảnh dọc
            String tenCotDHS1[] = {"MADHS", "DIACHI", "TAICHINH", "DONVI"};
            ArrayList<ArrayList<String>> duhocsinh_3 = db.getManhDuHocSinh(f1, tblmodel, tblResult, txtError, tenCotDHS1, "3"); // Server 2

            // * Gộp 3 mảnh ngang này với mảnh 1 (mảnh dọc)
//            String tenCotDuHocSinhAll[] = {"MADHS", "HOTEN", "DIEMTB", "IELTS", "DIACHI", "TAICHINH", "DONVI"};
            ArrayList<ArrayList<String>> duhocsinh = db.ket(combinedDuHocSinh, duhocsinh_3);

            // *---------------------------------------------
            // * Lấy tất cả dữ liệu Của bảng đăng ký du học với tham số tên trường
            String tenCotDKDH[] = {"MADHS", "MATR", "MANG", "TGDANGKY", "TGHOC"};
            tblmodel = new DefaultTableModel(tenCotDKDH, 0);

            // * Gộp 3 mảnh ngang của dữ liệu bảng đăng ký du học
            ArrayList<ArrayList<String>> dangkyduhoc_1 = db.getManhDangKyDuHoc(f1, tblmodel, tblResult, txtError, tenCotDKDH, "1"); // Server 1
            ArrayList<ArrayList<String>> dangkyduhoc_2 = db.getManhDangKyDuHoc(f1, tblmodel, tblResult, txtError, tenCotDKDH, "2"); // Server 1
            ArrayList<ArrayList<String>> dangkyduhoc_3 = db.getManhDangKyDuHoc(f1, tblmodel, tblResult, txtError, tenCotDKDH, "3"); // Server 2

            // * gộp 3 mảnh ngang của dữ liệu
            ArrayList<ArrayList<String>> dangkyduhoc = db.gopManh(dangkyduhoc_1, dangkyduhoc_2, dangkyduhoc_3);

            db.DanhSachDuHocSinhDangKy(tblmodel, tblResult, txtError, tenTruong, truonghoc, duhocsinh, dangkyduhoc);

        }

    }//GEN-LAST:event_btnDSDHSDKActionPerformed

    private void btnDHSRotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDHSRotActionPerformed
        // TODO add your handling code here:
        File f1 = new File("D:\\Download\\Data\\server_1.txt");
        File f2 = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        // * Lấy tất cả dữ liệu của bảng Du Học Sinh
        String tenCotDHS[] = {"MADHS", "HOTEN", "DIEMTB", "IELTS"};
        tblmodel = new DefaultTableModel(tenCotDHS, 0);

        // * Lay tat ca manh ngang
        ArrayList<ArrayList<String>> duhocsinh_1 = db.getManhDuHocSinh(f1, tblmodel, tblResult, txtError, tenCotDHS, "1"); // Server 1
        ArrayList<ArrayList<String>> duhocsinh_2 = db.getManhDuHocSinh(f1, tblmodel, tblResult, txtError, tenCotDHS, "2"); // Server 1

        // * gộp 2 mảnh ngang 
        ArrayList<ArrayList<String>> combinedDuHocSinh = db.gopManh(duhocsinh_1, duhocsinh_2);

        // * Lấy dữ liệu của mảnh dọc
        String tenCotDHS1[] = {"MADHS", "DIACHI", "TAICHINH", "DONVI"};
        ArrayList<ArrayList<String>> duhocsinh_3 = db.getManhDuHocSinh(f1, tblmodel, tblResult, txtError, tenCotDHS1, "3"); // Server 2

        // * Gộp 3 mảnh ngang này với mảnh 1 (mảnh dọc)
        ArrayList<ArrayList<String>> duhocsinh = db.ket(combinedDuHocSinh, duhocsinh_3);

        // *---------------------------------------------
        // * Lấy tất cả dữ liệu Của bảng đăng ký du học với tham số tên trường
        String tenCotDKDH[] = {"MADHS", "MATR", "MANG", "TGDANGKY", "TGHOC"};
        tblmodel = new DefaultTableModel(tenCotDKDH, 0);

        // * Gộp 3 mảnh ngang của dữ liệu bảng đăng ký du học
        ArrayList<ArrayList<String>> dangkyduhoc_1 = db.getManhDangKyDuHoc(f1, tblmodel, tblResult, txtError, tenCotDKDH, "1"); // Server 1
        ArrayList<ArrayList<String>> dangkyduhoc_2 = db.getManhDangKyDuHoc(f1, tblmodel, tblResult, txtError, tenCotDKDH, "2"); // Server 1
        ArrayList<ArrayList<String>> dangkyduhoc_3 = db.getManhDangKyDuHoc(f1, tblmodel, tblResult, txtError, tenCotDKDH, "3"); // Server 2

        // * gộp 3 mảnh ngang của dữ liệu
        ArrayList<ArrayList<String>> dangkyduhoc = db.gopManh(dangkyduhoc_1, dangkyduhoc_2, dangkyduhoc_3);

        // *---------------------------------------------
        String tenCotNG1[] = {"MANG", "TENNGANH", "IELTS"};
        tblmodel = new DefaultTableModel(tenCotNG1, 0);

        // * Lấy Mảnh 1
        ArrayList<ArrayList<String>> nganh_1 = db.getManhNganhHoc(f1, tblmodel, tblResult, txtError, tenCotNG1, "1"); // Server 1

        // * Lấy Mảnh 2
        String tenCotNG2[] = {"MANG", "SONAM"};
        ArrayList<ArrayList<String>> nganh_2 = db.getManhNganhHoc(f1, tblmodel, tblResult, txtError, tenCotNG2, "2"); // Server 2

        // * Gộp 2 mảnh ngang này với mảnh 1 (mảnh dọc)
        ArrayList<ArrayList<String>> nganhhoc = db.ket(nganh_1, nganh_2);
        db.DanhSachDuHocSinhRot(tblmodel, tblResult, txtError, dangkyduhoc, nganhhoc, duhocsinh);

    }//GEN-LAST:event_btnDHSRotActionPerformed

    private DefaultTableModel tblmodel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TenChuyenNghanh;
    private javax.swing.JButton btnDHSRot;
    private javax.swing.JButton btnDSCN;
    private javax.swing.JButton btnDSDHS;
    private javax.swing.JButton btnDSDHSDK;
    private javax.swing.JButton btnDSDHSDKCN;
    private javax.swing.JButton btnDST;
    private javax.swing.JButton btnDSTDDK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextArea txtError;
    private javax.swing.JTextField txtTenDuHocSinh;
    private javax.swing.JTextField txtTenTruong;
    // End of variables declaration//GEN-END:variables

}
