USE CSDLPTTH_08
-- Trường học 
CREATE TABLE TruongHoc_1 (
    MATR VARCHAR(10) PRIMARY KEY,
    HOCPHI INT
);
go
INSERT INTO TruongHoc_1 
SELECT MATR,HOCPHI FROM TruongHoc ;
go
CREATE TABLE TruongHoc_2 (
    MATR VARCHAR(10) PRIMARY KEY,
    TENTRUONG VARCHAR(255),
    QUOCGIA VARCHAR(100),
);
go
INSERT INTO TruongHoc_2
SELECT MATR,TENTRUONG,QUOCGIA FROM TruongHoc WHERE QUOCGIA = 'Ha Lan';
go
CREATE TABLE TruongHoc_3 ( 
    MATR VARCHAR(10) PRIMARY KEY,
    TENTRUONG VARCHAR(255),
    QUOCGIA VARCHAR(100),
);
go
CREATE TABLE TruongHoc_4 ( 
    MATR VARCHAR(10) PRIMARY KEY,
    TENTRUONG VARCHAR(255),
    QUOCGIA VARCHAR(100),
);
go


-- Du Học Sinh
CREATE TABLE DuHocSinh_1 (
    MADHS VARCHAR(10) PRIMARY KEY,
    HOTEN VARCHAR(100),
    DIEMTB FLOAT,
    IELTS FLOAT
);
go
INSERT INTO DuHocSinh_1 
SELECT MADHS,HOTEN,DIEMTB,IELTS FROM DuHocSinh WHERE DIEMTB >= 7.5;
go

CREATE TABLE DuHocSinh_2 (
    MADHS VARCHAR(10) PRIMARY KEY,
    HOTEN VARCHAR(100),
    DIEMTB FLOAT,
    IELTS FLOAT
);
go
INSERT INTO DuHocSinh_2 
SELECT MADHS,HOTEN,DIEMTB,IELTS FROM DuHocSinh WHERE DIEMTB < 7.5;
go
CREATE TABLE DuHocSinh_3 (
    MADHS VARCHAR(10) PRIMARY KEY,
    DIACHI VARCHAR(255),
	TAICHINH FLOAT,
    DONVI VARCHAR(10)
);
go

-- Ngành học
CREATE TABLE NganhHoc_1 (
    MANG VARCHAR(10) PRIMARY KEY,
    TENNGANH VARCHAR(255),
    IELTS FLOAT,
);
go
INSERT INTO NganhHoc_1 
SELECT MANG,TENNGANH,IELTS FROM NganhHoc ;
go
CREATE TABLE NganhHoc_2 (
    MANG VARCHAR(10) PRIMARY KEY,
    SONAM INT
);
go

-- Du Học Sinh Đăng Ký
CREATE TABLE DangKy_1 ( 
    MADHS VARCHAR(10),
    MATR VARCHAR(10),
    MANG VARCHAR(10),
    TGDANGKY DATE,
    TGHOC DATE,
    PRIMARY KEY (MADHS, MATR, MANG),
    FOREIGN KEY (MADHS) REFERENCES DuHocSinh(MADHS),
    FOREIGN KEY (MATR) REFERENCES TruongHoc(MATR),
    FOREIGN KEY (MANG) REFERENCES NganhHoc(MANG)
);
go
INSERT INTO DangKy_1
SELECT * FROM DangKyDuHoc WHERE MATR IN (SELECT MATR FROM TruongHoc_4 );
go
CREATE TABLE DangKy_2( 
    MADHS VARCHAR(10),
    MATR VARCHAR(10),
    MANG VARCHAR(10),
    TGDANGKY DATE,
    TGHOC DATE,
    PRIMARY KEY (MADHS, MATR, MANG),
    FOREIGN KEY (MADHS) REFERENCES DuHocSinh(MADHS),
    FOREIGN KEY (MATR) REFERENCES TruongHoc(MATR),
    FOREIGN KEY (MANG) REFERENCES NganhHoc(MANG)
);
go
INSERT INTO DangKy_2
SELECT * FROM DangKyDuHoc WHERE MATR IN (SELECT MATR FROM TruongHoc_2);
go
CREATE TABLE DangKy_3 ( 
    MADHS VARCHAR(10),
    MATR VARCHAR(10),
    MANG VARCHAR(10),
    TGDANGKY DATE,
    TGHOC DATE,
    PRIMARY KEY (MADHS, MATR, MANG),
    FOREIGN KEY (MADHS) REFERENCES DuHocSinh(MADHS),
    FOREIGN KEY (MATR) REFERENCES TruongHoc(MATR),
    FOREIGN KEY (MANG) REFERENCES NganhHoc(MANG)
);
